import javax.servlet.http.*;
import javax.servlet.*;
import java.io.*;
public class employ2 extends HttpServlet
{
 public void doGet(HttpServletRequest re,HttpServletResponse rs) throws ServletException,IOException
 {
  rs.setContentType("text/html");
  PrintWriter out=rs.getWriter();
  out.println("<html><TITLE>Document Title</TITLE><style>a{color:black}</style></HEAD>");
  out.println("<BODY bgcolor=skyblue text=black><form name=empma method=get action='http://localhost:8080/servlet/empadd'>");
  out.println("<font face=Verdana><h2 align=center>	Employee Details Management</h2>");
  out.println("<table><tr><td><font size=-2 face=Verdana><b>Employee Code</td>");
  out.println("<td><font size=-2 face=Verdana><input type=text name=t1 value= ></td>");
  out.println("<td><font size=-2 face=Verdana><b>Employee Name</td><td><font size=-2 face=Verdana><input type=text name=t2 value= ></td>");
  out.println("</tr><tr><td><font size=-2 face=Verdana><b>Email ID</td><td><font size=-2 face=Verdana><input type=text name=t3 value= > </td>");
  out.println("<td><font size=-2 face=Verdana><b>Qualification</td><td><font size=-2 face=Verdana>");
  out.println("  <select name=t4>");
  out.println("  <option name=1 value=M.E(CS)>M.E(CS)");
  out.println("  <option name=2 value=M.Tech(IT)>M.Tech(IT)");
  out.println("  <option name=3 value=B.E.(CS)>B.E.(CS)");
  out.println("  <option name=4 value=B.Tech(IT)>B.Tech(IT)");
  out.println("  <option name=5 value=MCA>MCA");
  out.println("  <option name=6 value=M.Sc(IT)>M.Sc(IT)");
  out.println("  <option name=7 value=M.Sc(CS)>M.Sc(CS)");
  out.println("  </select></td>");
  out.println("  </tr><tr><td><font size=-2 face=Verdana><b>Year of Experience </td><td><font size=-2 face=Verdana>");
  out.println("  <select name=t5>");
  out.println("  <option name=0>0");
  out.println("  <option name=1>1");
  out.println("  <option name=2>2");
  out.println("  <option name=3>3");
  out.println("  <option name=4>4");
  out.println("  <option name=5>5");
  out.println("  <option name=6>6");
  out.println("  <option name=7>7");
  out.println("  <option name=8>8");
  out.println("  <option name=9>9");
  out.println("  <option name=10>10");
  out.println("  <option name=11>11");
  out.println("  <option name=12>12");
  out.println("  <option name=13>13");
  out.println("  <option name=14>14");
  out.println("  <option name=15>15");
  out.println("  <option name=16>16");
  out.println("  <option name=17>17");
  out.println("  <option name=18>18");
  out.println("  <option name=19>19");
  out.println("  <option name=20>20");
  out.println("  <option name=21>21");
  out.println("  <option name=22>22");
  out.println("  <option name=23>23");
  out.println("  <option name=24>24");
  out.println("  <option name=25>25");
  out.println("  <option name=26>26");
  out.println("  <option name=27>27");
  out.println("  <option name=28>28");
  out.println("  <option name=29>29");
  out.println("  <option name=30>30");
  out.println("  <option name=31>31");
  out.println("  </select></td>");
  out.println("<td><font size=-2 face=Verdana><b>Previous Year Experience </td>");
  out.println("<td><font size=-2 face=Verdana><select name=t6>");
  out.println("  <option name=0>0");
  out.println("  <option name=1>1");
  out.println("  <option name=2>2");
  out.println("  <option name=3>3");
  out.println("  <option name=4>4");
  out.println("  <option name=5>5");
  out.println("  <option name=6>6");
  out.println("  <option name=7>7");
  out.println("  <option name=8>8");
  out.println("  <option name=9>9");
  out.println("  <option name=10>10");
  out.println("  <option name=11>11");
  out.println("  <option name=12>12");
  out.println("  <option name=13>13");
  out.println("  <option name=14>14");
  out.println("  <option name=15>15");
  out.println("  <option name=16>16");
  out.println("  <option name=17>17");
  out.println("  <option name=18>18");
  out.println("  <option name=19>19");
  out.println("  <option name=20>20");
  out.println("  <option name=21>21");
  out.println("  <option name=22>22");
  out.println("  <option name=23>23");
  out.println("  <option name=24>24");
  out.println("  <option name=25>25");
  out.println("  <option name=26>26");
  out.println("  <option name=27>27");
  out.println("  <option name=28>28");
  out.println("  <option name=29>29");
  out.println("  <option name=30>30");
  out.println("  <option name=31>31");
  out.println("  </select></td></tr>");  
  out.println("  <tr><td><font size=-2 face=Verdana><b>Blood Group</td>");
  out.println("  <td><font size=-2 face=Verdana><select name=t7>");
  out.println("  <option name=1 value=A+>A+");
  out.println("  <option name=2 value=A1+>A1+");
  out.println("  <option name=3 value=A->A-");
  out.println("  <option name=4 value=A1->A1-");
  out.println("  <option name=5 value=B+>B+");
  out.println("  <option name=6 value=B1+>B1+");
  out.println("  <option name=7 value=B->B-");
  out.println("  <option name=8 value=B1->B1-");
  out.println("  <option name=7 value=O+>O+");
  out.println("  <option name=8 value=O->O-"); 
  out.println("  <option name=7 value=AB+>AB+");
  out.println("  <option name=8 value=AB->AB-"); 
  out.println("  </select></td>");
  out.println("  <td><font size=-2 face=Verdana><b>Date of Birth</td><td><font size=-2 face=Verdana>");
  out.println("  <Select name=date>");
  out.println("  <option name=1>1");
  out.println("  <option name=2>2");
  out.println("  <option name=3>3");
  out.println("  <option name=4>4");
  out.println("  <option name=5>5");
  out.println("  <option name=6>6");
  out.println("  <option name=7>7");
  out.println("  <option name=8>8");
  out.println("  <option name=9>9");
  out.println("  <option name=10>10");
  out.println("  <option name=11>11");
  out.println("  <option name=12>12");
  out.println("  <option name=13>13");
  out.println("  <option name=14>14");
  out.println("  <option name=15>15");
  out.println("  <option name=16>16");
  out.println("  <option name=17>17");
  out.println("  <option name=18>18");
  out.println("  <option name=19>19");
  out.println("  <option name=20>20");
  out.println("  <option name=21>21");
  out.println("  <option name=22>22");
  out.println("  <option name=23>23");
  out.println("  <option name=24>24");
  out.println("  <option name=25>25");
  out.println("  <option name=26>26");
  out.println("  <option name=27>27");
  out.println("  <option name=28>28");
  out.println("  <option name=29>29");
  out.println("  <option name=30>30");
  out.println("  <option name=31>31");
  out.println("  </select>");
  out.println("  <select name=mon>");
  out.println("  <option name=1 value=jan>Jan"); 
  out.println("  <option name=2 value=feb>Feb");
  out.println("  <option name=3 value=mar>Mar");
  out.println("  <option name=4 value=apr>Apr");
  out.println("  <option name=5 value=may>May");
  out.println("  <option name=6 value=jun>jun");
  out.println("  <option name=7 value=jly>Jly");
  out.println("  <option name=8 value=aug>Aug");
  out.println("  <option name=9 value=sep>Sep");
  out.println("  <option name=10 value=oct>Oct");
  out.println("  <option name=11 value=nov>Nov");
  out.println("  <option name=12 value=dec>Dec");
  out.println("  </select>");
  out.println("  <select name=year>");
  out.println("  <option name=1 value=1970>1970");
  out.println("  <option name=2 value=1971>1971");
  out.println("  <option name=3 value=1972>1972");
  out.println("  <option name=4 value=1973>1973");
  out.println("  <option name=5 value=1974>1974");
  out.println("  <option name=6 value=1975>1975");
  out.println("  <option name=7 value=1976>1976");
  out.println("  <option name=8 value=1977>1977");
  out.println("  <option name=9 value=1978>1978");
  out.println("  <option name=10 value=1979>1979");
  out.println("  <option name=11 value=1980>1980");
  out.println("  <option name=12 value=1981>1981");
  out.println("  <option name=13 value=1982>1982");
  out.println("  <option name=14 value=1983>1983");
  out.println("  <option name=15 value=1984>1984");
  out.println("  <option name=16 value=1985>1985");
  out.println("  </select></td>");
  out.println("  </tr><tr><td><font size=-2 face=Verdana><b>Job Code</td><td><font size=-2 face=Verdana>");
  out.println("  <select name=t9>");
  out.println("  <option name=16 value=11>11");
  out.println("  <option name=16 value=12>12");
  out.println("  <option name=16 value=13>13");
  out.println("  <option name=16 value=14>14");
  out.println("  <option name=16 value=15>15");
  out.println("  <option name=16 value=16>16");
  out.println("  <option name=16 value=17>17");
  out.println("  <option name=16 value=18>18");
  out.println("  <option name=16 value=19>19");
  out.println("  <option name=16 value=20>20");
  out.println("  </select></td>");
  out.println("  <td><font size=-2 face=Verdana><b>Job Nature</td><td><font size=-2 face=Verdana><input type=text name=t10 value= ></td>");
  out.println("  </tr><tr><td><font size=-2 face=Verdana><b>Marritial  Status</td><td><font size=-2 face=Verdana>");
  out.println("  <Select name=t11>");
  out.println("  <option name=16 value=Married>Married");
  out.println("  <option name=16 value=UnMarried>UnMarried");
  out.println("  <option name=16 value=Widow>Widow");
  out.println("  </select></td>");
  out.println("<td><font size=-2 face=Verdana><b>Reference By</td><td><font size=-2 face=Verdana><input type=text name=t12 value=></td>");
  out.println("</tr><tr><td><font size=-2 face=Verdana><b>Present Adress</td><td><font size=-2 face=Verdana><textarea rows=5 cols=20 name=t13></textarea></td>");
  out.println("<td><font size=-2 face=Verdana><b>Permanent Address</td><td><font size=-2 face=Verdana><textarea rows=5 cols=20 name=t14></textarea></td>");
  out.println("</tr></table><br><br><br><center>		<input type=submit name=ad value='Add'> <input type=reset name=ss value='Cancel'> <br><br><a href='http://localhost:8080/servlet/employ'><b>Back</b></a>");
  out.println("</center></form></body></html>");
 }
}



