import javax.servlet.http.*;
import javax.servlet.*;
import java.io.*;
public class newuserlogin1 extends HttpServlet
{
 public void doGet(HttpServletRequest re,HttpServletResponse rs) throws ServletException,IOException
 {
  rs.setContentType("text/html");
  PrintWriter out=rs.getWriter();
  out.println("<html><body bgcolor=skyblue><center><style>a{color:black}</style><h4>Human Resource Management System</h4></center> <h1><center> New User Registration Form </center></h1>");
  out.println("<title> HRMS</title>  <form method=get action='http://localhost:8080/servlet/usersreg'>");
  out.println("  <table border=0 align=center>  <tr><td>User Name</td><td><input type=text name=t1></td></tr>");
  out.println("  <tr><td>Password </td><td><input type=password name=t2></td></tr>  <tr><td>Sex </td><td><select name=t3><option name=m>male<option name=f>female</td></select></tr>");
  out.println("  <tr><td>Date of birth </td><td><select name=date>");
  out.println("  <option name=1>1");
  out.println("  <option name=2>2");
  out.println("  <option name=3>3");
  out.println("  <option name=4>4");
  out.println("  <option name=5>5");
  out.println("  <option name=6>6");
  out.println("  <option name=7>7");
  out.println("  <option name=8>8");
  out.println("  <option name=9>9");
  out.println("  <option name=10>10");
  out.println("  <option name=11>11");
  out.println("  <option name=12>12");
  out.println("  <option name=13>13");
  out.println("  <option name=14>14");
  out.println("  <option name=15>15");
  out.println("  <option name=16>16");
  out.println("  <option name=17>17");
  out.println("  <option name=18>18");
  out.println("  <option name=19>19");
  out.println("  <option name=20>20");
  out.println("  <option name=21>21");
  out.println("  <option name=22>22");
  out.println("  <option name=23>23");
  out.println("  <option name=24>24");
  out.println("  <option name=25>25");
  out.println("  <option name=26>26");
  out.println("  <option name=27>27");
  out.println("  <option name=28>28");
  out.println("  <option name=29>29");
  out.println("  <option name=30>30");
  out.println("  <option name=31>31");
  out.println("  </select>");
  out.println("  <select name=mon>");
  out.println("  <option name=1 value=jan>Jan"); 
  out.println("  <option name=2 value=feb>Feb");
  out.println("  <option name=3 value=mar>Mar");
  out.println("  <option name=4 value=apr>Apr");
  out.println("  <option name=5 value=may>May");
  out.println("  <option name=6 value=jun>jun");
  out.println("  <option name=7 value=jly>Jly");
  out.println("  <option name=8 value=aug>Aug");
  out.println("  <option name=9 value=sep>Sep");
  out.println("  <option name=10 value=oct>Oct");
  out.println("  <option name=11 value=nov>Nov");
  out.println("  <option name=12 value=dec>Dec");
  out.println("  </select>");
  out.println("  <select name=year>");
  out.println("  <option name=1 value=1970>1970");
  out.println("  <option name=2 value=1971>1971");
  out.println("  <option name=3 value=1972>1972");
  out.println("  <option name=4 value=1973>1973");
  out.println("  <option name=5 value=1974>1974");
  out.println("  <option name=6 value=1975>1975");
  out.println("  <option name=7 value=1976>1976");
  out.println("  <option name=8 value=1977>1977");
  out.println("  <option name=9 value=1978>1978");
  out.println("  <option name=10 value=1979>1979");
  out.println("  <option name=11 value=1980>1980");
  out.println("  <option name=12 value=1981>1981");
  out.println("  <option name=13 value=1982>1982");
  out.println("  <option name=14 value=1983>1983");
  out.println("  <option name=15 value=1984>1984");
  out.println("  <option name=16 value=1985>1985");
  out.println("  </select></td></tr>");
  out.println("  <tr><td>Address </td><td><textarea rows=5 cols=20 name=t5></textarea></td></tr>");
  out.println("  <tr><td>City </td><td><input type=text name=t6></td></tr>  <tr><td>Country </td><td><input type=text name=t7></td></tr>");
  out.println("  <tr><td>Pin Code </td><td><input type=text name=pin></td></tr>");
  out.println("  <tr><td>Qualification</td><td><select name=t8>");
  out.println("  <option name=1 value=M.E(CS)>M.E(CS)");
  out.println("  <option name=2 value=M.Tech(IT)>M.Tech(IT)");
  out.println("  <option name=3 value=B.E.(CS)>B.E.(CS)");
  out.println("  <option name=4 value=B.Tech(IT)>B.Tech(IT)");
  out.println("  <option name=5 value=MCA>MCA");
  out.println("  <option name=6 value=M.Sc(IT)>M.Sc(IT)");
  out.println("  <option name=7 value=M.Sc(CS)>M.Sc(CS)");
  out.println("  </select></td></tr>");
  out.println("  <tr><td>Skills summary </td><td><textarea rows=5 cols=20 name=t9></textarea></td></tr>");
  out.println("  <tr><td>Phone </td><td><input type=text name=t10></td></tr>  <tr><td>Email </td><td><input type=text name=t11></textarea></td></tr>");
  out.println("  <tr><td>Email1 </td><td><input type=text name=t12></textarea></td></tr>  <tr><td colspan=2 align=center><input type=submit value='submit'></td></tr>");
  out.println("  </table>");
  out.println("  <br><center><b><a href='http://localhost:8080/servlet/home'><strong><font size=-1><b>Back</b></font></strong></a></center></form></body></html>");
 }
}