import javax.servlet.http.*;
import javax.servlet.*;
import java.io.*;
public class rectproject1 extends HttpServlet
{
 public void doGet(HttpServletRequest re,HttpServletResponse rs) throws ServletException,IOException
 {
  rs.setContentType("text/html");
  PrintWriter out=rs.getWriter();
  out.println("<html><head><title></title><style>a{color:black}</style></HEAD><BODY bgcolor=skyblue text=black>");
  out.println("<form name=vdata method=post action='http://localhost:8080/servlet/rectproject'><font face=Verdana>");
  out.println("<br><h2><p align=center>		Project Trainee Details</p></h2>");
  out.println("<table><tr><td><font face=Verdana size=-1><b> Recruitment Code</td><td><font face=Verdana size=-1><b><input type=text name=t1></td>");
  out.println("<td><font face=Verdana size=-1><b>Name</td>");
  out.println("<td><font face=Verdana size=-1><b><input type=text name=t2></td></tr>");
  out.println("<tr><td><font face=Verdana size=-1><b>Project Title</td>");
  out.println("<td><font face=Verdana size=-1><b>  <input type=text name=t3></td>");
  out.println("<td><font face=Verdana size=-1><b>Project Language</td><td><font face=Verdana size=-1><b><input type=text name=t4></td>");
  out.println("</tr><tr><td><font face=Verdana size=-1><b>Project Place</td>");
  out.println("<td><font face=Verdana size=-1><b><input type=text name=t5></td>");
  out.println(" </tr><tr><td><font face=Verdana size=-1><b>Project From Date</td>");
  out.println("<td><font face=Verdana size=-1><b>");
  out.println("  <Select name=sdate>");
  out.println("  <option name=1>1");
  out.println("  <option name=2>2");
  out.println("  <option name=3>3");
  out.println("  <option name=4>4");
  out.println("  <option name=5>5");
  out.println("  <option name=6>6");
  out.println("  <option name=7>7");
  out.println("  <option name=8>8");
  out.println("  <option name=9>9");
  out.println("  <option name=10>10");
  out.println("  <option name=11>11");
  out.println("  <option name=12>12");
  out.println("  <option name=13>13");
  out.println("  <option name=14>14");
  out.println("  <option name=15>15");
  out.println("  <option name=16>16");
  out.println("  <option name=17>17");
  out.println("  <option name=18>18");
  out.println("  <option name=19>19");
  out.println("  <option name=20>20");
  out.println("  <option name=21>21");
  out.println("  <option name=22>22");
  out.println("  <option name=23>23");
  out.println("  <option name=24>24");
  out.println("  <option name=25>25");
  out.println("  <option name=26>26");
  out.println("  <option name=27>27");
  out.println("  <option name=28>28");
  out.println("  <option name=29>29");
  out.println("  <option name=30>30");
  out.println("  <option name=31>31");
  out.println("  </select>");
  out.println("  <select name=smon>");
  out.println("  <option name=1 value=jan>Jan"); 
  out.println("  <option name=2 value=feb>Feb");
  out.println("  <option name=3 value=mar>Mar");
  out.println("  <option name=4 value=apr>Apr");
  out.println("  <option name=5 value=may>May");
  out.println("  <option name=6 value=jun>jun");
  out.println("  <option name=7 value=jly>Jly");
  out.println("  <option name=8 value=aug>Aug");
  out.println("  <option name=9 value=sep>Sep");
  out.println("  <option name=10 value=oct>Oct");
  out.println("  <option name=11 value=nov>Nov");
  out.println("  <option name=12 value=dec>Dec");
  out.println("  </select>");
  out.println("  <select name=syear>");
  out.println("  <option name=1 value=2000>2000");
  out.println("  <option name=2 value=2001>2001");
  out.println("  <option name=3 value=2002>2002");
  out.println("  <option name=4 value=2003>2003");
  out.println("  <option name=5 value=2004>2004");
  out.println("  <option name=6 value=2005>2005");
  out.println("  </select></td>");
  out.println("<td><font face=Verdana size=-1><b>Project To Date</td><td><font face=Verdana size=-1><b>");
  out.println("  <Select name=edate>");
  out.println("  <option name=1>1");
  out.println("  <option name=2>2");
  out.println("  <option name=3>3");
  out.println("  <option name=4>4");
  out.println("  <option name=5>5");
  out.println("  <option name=6>6");
  out.println("  <option name=7>7");
  out.println("  <option name=8>8");
  out.println("  <option name=9>9");
  out.println("  <option name=10>10");
  out.println("  <option name=11>11");
  out.println("  <option name=12>12");
  out.println("  <option name=13>13");
  out.println("  <option name=14>14");
  out.println("  <option name=15>15");
  out.println("  <option name=16>16");
  out.println("  <option name=17>17");
  out.println("  <option name=18>18");
  out.println("  <option name=19>19");
  out.println("  <option name=20>20");
  out.println("  <option name=21>21");
  out.println("  <option name=22>22");
  out.println("  <option name=23>23");
  out.println("  <option name=24>24");
  out.println("  <option name=25>25");
  out.println("  <option name=26>26");
  out.println("  <option name=27>27");
  out.println("  <option name=28>28");
  out.println("  <option name=29>29");
  out.println("  <option name=30>30");
  out.println("  <option name=31>31");
  out.println("  </select>");
  out.println("  <select name=emon>");
  out.println("  <option name=1 value=jan>Jan"); 
  out.println("  <option name=2 value=feb>Feb");
  out.println("  <option name=3 value=mar>Mar");
  out.println("  <option name=4 value=apr>Apr");
  out.println("  <option name=5 value=may>May");
  out.println("  <option name=6 value=jun>jun");
  out.println("  <option name=7 value=jly>Jly");
  out.println("  <option name=8 value=aug>Aug");
  out.println("  <option name=9 value=sep>Sep");
  out.println("  <option name=10 value=oct>Oct");
  out.println("  <option name=11 value=nov>Nov");
  out.println("  <option name=12 value=dec>Dec");
  out.println("  </select>");
  out.println("  <select name=eyear>");
  out.println("  <option name=1 value=2000>2000");
  out.println("  <option name=2 value=2001>2001");
  out.println("  <option name=3 value=2002>2002");
  out.println("  <option name=4 value=2003>2003");
  out.println("  <option name=5 value=2004>2004");
  out.println("  <option name=6 value=2005>2005");
  out.println("  </select></td>");
  out.println("  </tr><tr> <td><font face=Verdana size=-1><b>Date Of Interview </td>");
  out.println("  <td><font face=Verdana size=-1><b>"); 
  out.println("  <Select name=idate>");
  out.println("  <option name=1>1");
  out.println("  <option name=2>2");
  out.println("  <option name=3>3");
  out.println("  <option name=4>4");
  out.println("  <option name=5>5");
  out.println("  <option name=6>6");
  out.println("  <option name=7>7");
  out.println("  <option name=8>8");
  out.println("  <option name=9>9");
  out.println("  <option name=10>10");
  out.println("  <option name=11>11");
  out.println("  <option name=12>12");
  out.println("  <option name=13>13");
  out.println("  <option name=14>14");
  out.println("  <option name=15>15");
  out.println("  <option name=16>16");
  out.println("  <option name=17>17");
  out.println("  <option name=18>18");
  out.println("  <option name=19>19");
  out.println("  <option name=20>20");
  out.println("  <option name=21>21");
  out.println("  <option name=22>22");
  out.println("  <option name=23>23");
  out.println("  <option name=24>24");
  out.println("  <option name=25>25");
  out.println("  <option name=26>26");
  out.println("  <option name=27>27");
  out.println("  <option name=28>28");
  out.println("  <option name=29>29");
  out.println("  <option name=30>30");
  out.println("  <option name=31>31");
  out.println("  </select>");
  out.println("  <select name=imon>");
  out.println("  <option name=1 value=jan>Jan"); 
  out.println("  <option name=2 value=feb>Feb");
  out.println("  <option name=3 value=mar>Mar");
  out.println("  <option name=4 value=apr>Apr");
  out.println("  <option name=5 value=may>May");
  out.println("  <option name=6 value=jun>jun");
  out.println("  <option name=7 value=jly>Jly");
  out.println("  <option name=8 value=aug>Aug");
  out.println("  <option name=9 value=sep>Sep");
  out.println("  <option name=10 value=oct>Oct");
  out.println("  <option name=11 value=nov>Nov");
  out.println("  <option name=12 value=dec>Dec");
  out.println("  </select>");
  out.println("  <select name=iyear>");
  out.println("  <option name=1 value=2000>2000");
  out.println("  <option name=2 value=2001>2001");
  out.println("  <option name=3 value=2002>2002");
  out.println("  <option name=4 value=2003>2003");
  out.println("  <option name=5 value=2004>2004");
  out.println("  <option name=6 value=2005>2005");
  out.println("  </select></td>");
  out.println("  <td><font face=Verdana size=-1><b>Email ID </td>");
  out.println("<td><font face=Verdana size=-1><b><input type=text name=t9></td>");
  out.println("</tr><tr> <td><font face=Verdana size=-1><b>Address </td>");
  out.println("<td><font face=Verdana size=-1><b><textarea name=t10 cols=17 rows=2></textarea>	</td>");
  out.println(" <td><font face=Verdana size=-1><b>Qualification </td><td><font face=Verdana size=-1><b>");
  out.println("  <select name=t11>");
  out.println("  <option name=1 value=M.E(CS)>M.E(CS)");
  out.println("  <option name=2 value=M.Tech(IT)>M.Tech(IT)");
  out.println("  <option name=3 value=B.E.(CS)>B.E.(CS)");
  out.println("  <option name=4 value=B.Tech(IT)>B.Tech(IT)");
  out.println("  <option name=5 value=MCA>MCA");
  out.println("  <option name=6 value=M.Sc(IT)>M.Sc(IT)");
  out.println("  <option name=7 value=M.Sc(CS)>M.Sc(CS)");
  out.println("  </select></td>");
  out.println("</tr></table><br><br><br><center> <input type=submit name=send value=Send>  <input type=reset name=submit value=cancel> ");
  out.println(" <a href='http://localhost:8080/servlet/recruitment'><font size=-1><b>Back</b></font></a></center></form>");
  out.println("</body></html>");
 }
}




