import javax.servlet.http.*;
import javax.servlet.*;
import java.io.*;
public class tempemploy2 extends HttpServlet
{
 public void doGet(HttpServletRequest re,HttpServletResponse rs) throws ServletException,IOException
 {
  rs.setContentType("text/html");
  PrintWriter out=rs.getWriter();
  out.println("<html><TITLE>Document Title</TITLE><style>a{color:black}</style></HEAD>");
  out.println("<BODY bgcolor=skyblue text=black><form name=empma method=get action='http://localhost:8080/servlet/tempadd'>");
  out.println("<font face=Verdana><h2 align=center>	Employee Details Management");
  out.println("</h2><br><br><center><table>");
  out.println("<tr><td><font size=-2 face=Verdana><b>Employee Code</td><td><font size=-2 face=Verdana><input type=text name=t1 value= ></td>");
  out.println("<td><font size=-2 face=Verdana><b>Employee Name</td><td><font size=-2 face=Verdana><input type=text name=t2 value= ></td>");
  out.println("</tr><tr><td><font size=-2 face=Verdana><b>Email ID</td>");
  out.println("<td><font size=-2 face=Verdana><input type=text name=t3 value= > </td><td><font size=-2 face=Verdana><b>Job Code</td>");
  out.println("<td><font size=-2 face=Verdana>");
  out.println("  <select name=t4>");
  out.println("  <option name=16 value=11>11");
  out.println("  <option name=16 value=12>12");
  out.println("  <option name=16 value=13>13");
  out.println("  <option name=16 value=14>14");
  out.println("  <option name=16 value=15>15");
  out.println("  <option name=16 value=16>16");
  out.println("  <option name=16 value=17>17");
  out.println("  <option name=16 value=18>18");
  out.println("  <option name=16 value=19>19");
  out.println("  <option name=16 value=20>20");
  out.println("  </select></td></tr>");
  out.println("<tr><td><font size=-2 face=Verdana><b>Train Category </td>");
  out.println("<td><font size=-2 face=Verdana><input type=text name=t5 value= ></td><td><font size=-2 face=Verdana><b>Train Place </td>");
  out.println("<td><font size=-2 face=Verdana><input type=text name=t6 value= ></td></tr>");
  out.println("<tr><td><font size=-2 face=Verdana><b>Training Start Date</td>");
  out.println("<td><font size=-2 face=Verdana>");
  out.println("  <Select name=sdate>");
  out.println("  <option name=1>1");
  out.println("  <option name=2>2");
  out.println("  <option name=3>3");
  out.println("  <option name=4>4");
  out.println("  <option name=5>5");
  out.println("  <option name=6>6");
  out.println("  <option name=7>7");
  out.println("  <option name=8>8");
  out.println("  <option name=9>9");
  out.println("  <option name=10>10");
  out.println("  <option name=11>11");
  out.println("  <option name=12>12");
  out.println("  <option name=13>13");
  out.println("  <option name=14>14");
  out.println("  <option name=15>15");
  out.println("  <option name=16>16");
  out.println("  <option name=17>17");
  out.println("  <option name=18>18");
  out.println("  <option name=19>19");
  out.println("  <option name=20>20");
  out.println("  <option name=21>21");
  out.println("  <option name=22>22");
  out.println("  <option name=23>23");
  out.println("  <option name=24>24");
  out.println("  <option name=25>25");
  out.println("  <option name=26>26");
  out.println("  <option name=27>27");
  out.println("  <option name=28>28");
  out.println("  <option name=29>29");
  out.println("  <option name=30>30");
  out.println("  <option name=31>31");
  out.println("  </select>");
  out.println("  <select name=smon>");
  out.println("  <option name=1 value=jan>Jan"); 
  out.println("  <option name=2 value=feb>Feb");
  out.println("  <option name=3 value=mar>Mar");
  out.println("  <option name=4 value=apr>Apr");
  out.println("  <option name=5 value=may>May");
  out.println("  <option name=6 value=jun>jun");
  out.println("  <option name=7 value=jly>Jly");
  out.println("  <option name=8 value=aug>Aug");
  out.println("  <option name=9 value=sep>Sep");
  out.println("  <option name=10 value=oct>Oct");
  out.println("  <option name=11 value=nov>Nov");
  out.println("  <option name=12 value=dec>Dec");
  out.println("  </select>");
  out.println("  <select name=syear>");
  out.println("  <option name=1 value=2000>2000");
  out.println("  <option name=2 value=2001>2001");
  out.println("  <option name=3 value=2002>2002");
  out.println("  <option name=4 value=2003>2003");
  out.println("  <option name=5 value=2004>2004");
  out.println("  <option name=6 value=2005>2005");
  out.println("  </select></td>");
  out.println("<td><font size=-2 face=Verdana><b>Training End Date</td><td><font size=-2 face=Verdana>");
  out.println("  <Select name=edate>");
  out.println("  <option name=1>1");
  out.println("  <option name=2>2");
  out.println("  <option name=3>3");
  out.println("  <option name=4>4");
  out.println("  <option name=5>5");
  out.println("  <option name=6>6");
  out.println("  <option name=7>7");
  out.println("  <option name=8>8");
  out.println("  <option name=9>9");
  out.println("  <option name=10>10");
  out.println("  <option name=11>11");
  out.println("  <option name=12>12");
  out.println("  <option name=13>13");
  out.println("  <option name=14>14");
  out.println("  <option name=15>15");
  out.println("  <option name=16>16");
  out.println("  <option name=17>17");
  out.println("  <option name=18>18");
  out.println("  <option name=19>19");
  out.println("  <option name=20>20");
  out.println("  <option name=21>21");
  out.println("  <option name=22>22");
  out.println("  <option name=23>23");
  out.println("  <option name=24>24");
  out.println("  <option name=25>25");
  out.println("  <option name=26>26");
  out.println("  <option name=27>27");
  out.println("  <option name=28>28");
  out.println("  <option name=29>29");
  out.println("  <option name=30>30");
  out.println("  <option name=31>31");
  out.println("  </select>");
  out.println("  <select name=emon>");
  out.println("  <option name=1 value=jan>Jan"); 
  out.println("  <option name=2 value=feb>Feb");
  out.println("  <option name=3 value=mar>Mar");
  out.println("  <option name=4 value=apr>Apr");
  out.println("  <option name=5 value=may>May");
  out.println("  <option name=6 value=jun>jun");
  out.println("  <option name=7 value=jly>Jly");
  out.println("  <option name=8 value=aug>Aug");
  out.println("  <option name=9 value=sep>Sep");
  out.println("  <option name=10 value=oct>Oct");
  out.println("  <option name=11 value=nov>Nov");
  out.println("  <option name=12 value=dec>Dec");
  out.println("  </select>");
  out.println("  <select name=eyear>");
  out.println("  <option name=1 value=2000>2000");
  out.println("  <option name=2 value=2001>2001");
  out.println("  <option name=3 value=2002>2002");
  out.println("  <option name=4 value=2003>2003");
  out.println("  <option name=5 value=2004>2004");
  out.println("  <option name=6 value=2005>2005");
  out.println("  </select></td>");
  out.println("</tr><tr><td><font size=-2 face=Verdana><b>Train Person</td>");
  out.println("<td><font size=-2 face=Verdana><input type=text name=t9 value= ></td></tr>");
  out.println("</table></center><br><br><br><center>");
  out.println("		<input type=submit name=ad value='Add'> <input type=reset name=ss value='Cancel'> <br><br><a href='http://localhost:8080/servlet/amodule'><b>Back</b></a>");
  out.println("</center>");
  out.println("</form></body></html>");
 }
}



